// ✅ market_data.js — перенесені всі компанії сюди

const competitors = [
    { name: "TechCorp", sector: "Технології", capital: "$1B", address: "Silicon Valley", financials: "Стабільний ріст", trends: "AI, Cloud", opportunities: "Розширення на Європу", employees: "5000", marketShare: "25%", founded: "2008", ceo: "John Smith", image: "images/graphic_up.jpg", revenue: "$250M", expenses: "$100M" },
    { name: "FinServe", sector: "Фінанси", capital: "$500M", address: "London, UK", financials: "Прибуток зростає", trends: "Fintech, Blockchain", opportunities: "Нові фінансові послуги", employees: "1200", marketShare: "15%", founded: "2015", ceo: "Emma Johnson", image: "images/graphic_down.jpg", revenue: "$180M", expenses: "$70M" },
    { name: "EnergyNet", sector: "Енергетика", capital: "$2B", address: "Berlin, Germany", financials: "Висока стабільність", trends: "Зелена енергетика", opportunities: "Інвестиції в нові технології", employees: "8000", marketShare: "30%", founded: "2000", ceo: "Michael Brown", image: "images/graphic_down.jpg", revenue: "$600M", expenses: "$320M" },
    { name: "AutoDrive", sector: "Автомобілі", capital: "$3B", address: "Detroit, USA", financials: "Постійне зростання", trends: "Електрокари, Автопілот", opportunities: "Розширення на азійський ринок", employees: "10000", marketShare: "20%", founded: "2012", ceo: "David White", image: "images/graphic_down.jpg", revenue: "$750M", expenses: "$400M" },
    { name: "FoodTech", sector: "Харчова промисловість", capital: "$700M", address: "Paris, France", financials: "Інноваційні продукти", trends: "Альтернативні білки", opportunities: "Глобальне розширення", employees: "3500", marketShare: "10%", founded: "2010", ceo: "Sophie Martin", image: "images/graphic_up.jpg", revenue: "$220M", expenses: "$110M" },
    { name: "EduTech", sector: "Освіта", capital: "$900M", address: "Toronto, Canada", financials: "Швидке зростання", trends: "Онлайн-навчання", opportunities: "Корпоративний сегмент", employees: "2500", marketShare: "12%", founded: "2017", ceo: "Robert King", image: "images/graphic_down.jpg", revenue: "$300M", expenses: "$140M" },
    { name: "HealthPlus", sector: "Медицина", capital: "$2.5B", address: "Zurich, Switzerland", financials: "Стабільний ріст", trends: "Дистанційна медицина", opportunities: "Інвестиції в AI", employees: "7500", marketShare: "28%", founded: "1995", ceo: "Laura Green", image: "images/graphic_up.jpg", revenue: "$800M", expenses: "$400M" },
    { name: "CloudSync", sector: "Хмарні технології", capital: "$1.2B", address: "Seattle, USA", financials: "Зростання клієнтів", trends: "Кібербезпека", opportunities: "Бізнес-рішення", employees: "6800", marketShare: "22%", founded: "2005", ceo: "Richard Adams", image: "images/graphic_up.jpg", revenue: "$400M", expenses: "$210M" },
    { name: "AgroNova", sector: "Сільське господарство", capital: "$600M", address: "Kyiv, Ukraine", financials: "Сезонне зростання", trends: "AgriTech, Дрони", opportunities: "Автоматизація ферм", employees: "2300", marketShare: "9%", founded: "2014", ceo: "Oleh Shevchenko", image: "images/graphic_up.jpg", revenue: "$170M", expenses: "$80M" },
    { name: "BuildSmart", sector: "Інфраструктура", capital: "$1.8B", address: "Warsaw, Poland", financials: "Нестабільна динаміка", trends: "Smart Cities", opportunities: "Публічні тендери", employees: "5400", marketShare: "16%", founded: "2001", ceo: "Anna Kowalska", image: "images/graphic_down.jpg", revenue: "$320M", expenses: "$250M" },
    { name: "RoboWare", sector: "Робототехніка", capital: "$2.1B", address: "Tokyo, Japan", financials: "Інтенсивне зростання", trends: "Промислові роботи", opportunities: "Світовий ринок", employees: "7200", marketShare: "18%", founded: "1999", ceo: "Takeshi Nakamura", image: "images/graphic_up.jpg", revenue: "$540M", expenses: "$300M" },
    { name: "TransLogix", sector: "Логістика", capital: "$850M", address: "Hamburg, Germany", financials: "Стабільність", trends: "Автоматизація складів", opportunities: "Міжнародні перевезення", employees: "4100", marketShare: "14%", founded: "2007", ceo: "Karl Meier", image: "images/graphic_down.jpg", revenue: "$280M", expenses: "$160M" },
    { name: "BioGenics", sector: "Біотехнології", capital: "$1.6B", address: "Boston, USA", financials: "Інноваційний прорив", trends: "Генна інженерія", opportunities: "Ліцензування патентів", employees: "3900", marketShare: "19%", founded: "2011", ceo: "Jessica Brown", image: "images/graphic_up.jpg", revenue: "$470M", expenses: "$230M" }
];

// 🔁 Доступ до масиву для інших скриптів
window.marketCompetitors = competitors;